### ISSUE TITLE
Unable to upload files: Maven group, artifact or version defined in the pom file do not match the file path

### ISSUE THREAD

**Issue by sinwe** [bintray/gradle-bintray-plugin#242]
I'm trying to upload my scala library that is build using gradle to bintray, but got the following error:

> HTTP/1.1 400 Bad Request [message:Unable to upload files: Maven group, artifact or version defined in the pom file do not match the file path 'value: io/projectreactor/value: reactor-scala-extensions_2.11/value: 0.3.5/value: reactor-scala-extensions_2.11-value: 0.3.5.pom']

I've verified that the pom file contains the correct value on the group, artifact and version. So I'm confused now.

**Comment by sinwe** [comment]
Turns out this issue is fixed in version 1.8.1.
I'm closing this.

**Comment by brunocarneiro** [comment]
I still received the error even though using '1.8.4' (and '1.8.1') version when I tried to upload the '1.0.0' version of my artifact.
Other version numbers such as '0.0.2' or '1.0.0-final' worked fine.

**Comment by AliKhoshraftar** [comment]
I have same problem with '1.8.4'
