### ISSUE TITLE
Unspecified version in 1.8.2

### ISSUE THREAD

**Issue by rapekas** [bintray/gradle-bintray-plugin#244]
Hi,

This cannot reproduce on 1.8.0.

When I use version 1.8.2 to upload artifacts from https://github.com/cuba-platform/sample-base (currently version 1.3.0 of sample is actual), I get double versions after upload: '1.3.0' and 'unspecified'. I expected to get '1.3.0' only.

![default](https://user-images.githubusercontent.com/6643040/41710144-ff6d4368-7555-11e8-9ec2-068ecfc49084.png)

To reproduce this, clone the sample-base, then open `build.gradle` and add the following line into `buildscript dependencies{}` section:
```java
 classpath "com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.2"
```
Then add the following text to the end of file:
```java
subprojects {
    apply plugin: 'com.jfrog.bintray'

    bintray {
        user = project.hasProperty('bintrayUser') ? project.property('bintrayUser') : System.getenv('BINTRAY_USER')
        key = project.hasProperty('bintrayApiKey') ? project.property('bintrayApiKey') : System.getenv('BINTRAY_API_KEY')

        configurations = ['archives']

        // make files public ?
        publish = false
        // override existing artifacts?
        override = false

        // metadata
        pkg {
            repo = '<your-test-repo>'
            name = 'sample-base'
            desc = 'Base app component for CUBA online demos' // Optional package description
            userOrg = '<your-org>'

            websiteUrl = 'https://github.com/cuba-platform/sample-base'
            issueTrackerUrl = 'https://github.com/cuba-platform/sample-base/issues'
            vcsUrl = 'https://github.com/cuba-platform/sample-base' // Mandatory for Open Source projects

            licenses = ["Apache-2.0"]

            labels = ['cuba-sample']
            githubRepo = 'cuba-platform/sample-base' // Optional Github repository
            githubReleaseNotesFile = 'README.md' // Optional Github readme file

            // Use line below or  command parameter -Pcuba.artifact.version=1.3.0
            version {
                released  = new Date()
                vcsTag = '1.3.0'
            }
        }
    }
}
```
To upload files, run `./gradlew clean assemble bintrayUpload`

**Comment by AlexeiVainshtein** [comment]
Hi @rapekas 

Thank you for reporting this and providing a sample project to reproduce this issue. We have found the root cause for this (commit 3fe02dfdae3e807afba57e0140a0d4c2424674e1). A new version should be released in the upcoming weeks.

Thanks,

**Comment by snowe2010** [comment]
@AlexeiVainshtein how soon can we expect a new version to be released?

**Comment by eyalbe4** [comment]
@rapekas and @snowe2010,
We've just released version 1.8.3 with this fix.
We would appreciate your feedback for it.

**Comment by snowe2010** [comment]
@eyalbe4 Is there a way to check which version of the plugin is being used? I'm resolving the bintray plugin through the nebula plugin and it still appears to be having the same issue. 

```
> Task :bintrayUpload
Task ':bintrayUpload' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Gradle Bintray Plugin version: 1.8.1
Version 'snowe/maven/Axon-Kotlin/unspecified' does not exist. Attempting to create it...
(Dry run) Created version 'snowe/maven/Axon-Kotlin/unspecified'.
Uploading to https://api.bintray.com/content/snowe/maven/Axon-Kotlin/unspecified/com/tylerthrailkill/axon-kotlin/0.0.3/axon-kotlin-0.0.3-sources.jar...
(Dry run) Uploaded to 'https://api.bintray.com/content/snowe/maven/Axon-Kotlin/unspecified/com/tylerthrailkill/axon-kotlin/0.0.3/axon-kotlin-0.0.3-sources.jar'.
Uploading to https://api.bintray.com/content/snowe/maven/Axon-Kotlin/unspecified/com/tylerthrailkill/axon-kotlin/0.0.3/axon-kotlin-0.0.3-javadoc.jar...
(Dry run) Uploaded to 'https://api.bintray.com/content/snowe/maven/Axon-Kotlin/unspecified/com/tylerthrailkill/axon-kotlin/0.0.3/axon-kotlin-0.0.3-javadoc.jar'.
Uploading to https://api.bintray.com/content/snowe/maven/Axon-Kotlin/unspecified/com/tylerthrailkill/axon-kotlin/0.0.3/axon-kotlin-0.0.3.jar...
(Dry run) Uploaded to 'https://api.bintray.com/content/snowe/maven/Axon-Kotlin/unspecified/com/tylerthrailkill/axon-kotlin/0.0.3/axon-kotlin-0.0.3.jar'.
Uploading to https://api.bintray.com/content/snowe/maven/Axon-Kotlin/unspecified/com/tylerthrailkill/axon-kotlin/0.0.3/axon-kotlin-0.0.3.pom...
(Dry run) Uploaded to 'https://api.bintray.com/content/snowe/maven/Axon-Kotlin/unspecified/com/tylerthrailkill/axon-kotlin/0.0.3/axon-kotlin-0.0.3.pom'.
:bintrayUpload (Thread[Task worker for ':',5,main]) completed. Took 0.357 secs.
:bintrayPublish (Thread[Task worker for ':',5,main]) started.
```

**Comment by snowe2010** [comment]
wow. I don't know what to say. the version was right there in the output 🤦‍♂️ 

Ignore my previous comment please.

**Comment by snowe2010** [comment]
@eyalbe4 I'm still seeing it attempt to use `unspecified`, though no more unspecified versions are getting uploaded. Now I'm having a 'duplicate'? packages being uploaded and this failure message

```
> Task :axon-kotlin:bintrayUpload
Task ':axon-kotlin:bintrayUpload' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Gradle Bintray Plugin version: 1.8.4
Uploading to https://api.bintray.com/content/snowe/maven/Axon-Kotlin/0.1.5/com/tylerthrailkill/axon-kotlin/0.1.5/axon-kotlin-0.1.5-sources.jar...
Uploaded to 'https://api.bintray.com/content/snowe/maven/Axon-Kotlin/0.1.5/com/tylerthrailkill/axon-kotlin/0.1.5/axon-kotlin-0.1.5-sources.jar'.
Uploading to https://api.bintray.com/content/snowe/maven/Axon-Kotlin/0.1.5/com/tylerthrailkill/axon-kotlin/0.1.5/axon-kotlin-0.1.5-javadoc.jar...
Uploaded to 'https://api.bintray.com/content/snowe/maven/Axon-Kotlin/0.1.5/com/tylerthrailkill/axon-kotlin/0.1.5/axon-kotlin-0.1.5-javadoc.jar'.
Uploading to https://api.bintray.com/content/snowe/maven/Axon-Kotlin/0.1.5/com/tylerthrailkill/axon-kotlin/0.1.5/axon-kotlin-0.1.5.jar...
Uploaded to 'https://api.bintray.com/content/snowe/maven/Axon-Kotlin/0.1.5/com/tylerthrailkill/axon-kotlin/0.1.5/axon-kotlin-0.1.5.jar'.
Uploading to https://api.bintray.com/content/snowe/maven/Axon-Kotlin/0.1.5/com/tylerthrailkill/axon-kotlin/0.1.5/axon-kotlin-0.1.5.pom...
Uploaded to 'https://api.bintray.com/content/snowe/maven/Axon-Kotlin/0.1.5/com/tylerthrailkill/axon-kotlin/0.1.5/axon-kotlin-0.1.5.pom'.
:axon-kotlin:bintrayUpload (Thread[Task worker for ':',5,main]) completed. Took 2.107 secs.
:bintrayUpload (Thread[Task worker for ':',5,main]) started.

> Task :bintrayUpload FAILED
Task ':bintrayUpload' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Gradle Bintray Plugin version: 1.8.4
Package 'axon-kotlin' does not exist. Attempting to create it...
:bintrayUpload (Thread[Task worker for ':',5,main]) completed. Took 0.32 secs.
:bintrayPublish (Thread[Task worker for ':',5,main]) started.

> Task :bintrayPublish FAILED
Task ':bintrayPublish' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
:bintrayPublish (Thread[Task worker for ':',5,main]) completed. Took 0.045 secs.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':bintrayUpload'.
> Could not create package 'nebula/gradle-plugins/axon-kotlin': HTTP/1.1 403 Forbidden [message:forbidden]

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':bintrayUpload'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:246)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:136)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.execute(DefaultTaskPlanExecutor.java:201)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.executeWithTask(DefaultTaskPlanExecutor.java:192)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: Could not create package 'nebula/gradle-plugins/axon-kotlin': HTTP/1.1 403 Forbidden [message:forbidden]
        at com.jfrog.bintray.gradle.tasks.BintrayUploadTask$_checkAndCreatePackage_closure8$_closure19.doCall(BintrayUploadTask.groovy:291)
        at groovyx.net.http.HTTPBuilder$1.handleResponse(HTTPBuilder.java:503)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
        at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:515)
        at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:434)
        at groovyx.net.http.HTTPBuilder.request(HTTPBuilder.java:383)
        at groovyx.net.http.HTTPBuilder$request$0.call(Unknown Source)
        at com.jfrog.bintray.gradle.tasks.BintrayUploadTask.checkAndCreatePackage(BintrayUploadTask.groovy:274)
        at com.jfrog.bintray.gradle.tasks.BintrayUploadTask.bintrayUpload(BintrayUploadTask.groovy:236)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more

==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':bintrayPublish'.
> Could not sign version 'unspecified': HTTP/1.1 404 Not Found [message:Package 'axon-kotlin' was not found]

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':bintrayPublish'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:246)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:136)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.execute(DefaultTaskPlanExecutor.java:201)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.executeWithTask(DefaultTaskPlanExecutor.java:192)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.api.GradleException: Could not sign version 'unspecified': HTTP/1.1 404 Not Found [message:Package 'axon-kotlin' was not found]
        at sun.reflect.GeneratedConstructorAccessor477.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
        at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
        at com.jfrog.bintray.gradle.tasks.BintrayPublishTask$_gpgSignVersion_closure1$_closure5.doCall(BintrayPublishTask.groovy:83)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovyx.net.http.HTTPBuilder$1.handleResponse(HTTPBuilder.java:503)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
        at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:515)
        at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:434)
        at groovyx.net.http.HTTPBuilder.request(HTTPBuilder.java:383)
        at groovyx.net.http.HTTPBuilder$request$0.call(Unknown Source)
        at com.jfrog.bintray.gradle.tasks.BintrayPublishTask.gpgSignVersion(BintrayPublishTask.groovy:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:190)
        at com.jfrog.bintray.gradle.tasks.BintrayPublishTask.signPublishAndSync(BintrayPublishTask.groovy:53)
        at com.jfrog.bintray.gradle.tasks.BintrayPublishTask.taskAction(BintrayPublishTask.groovy:25)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 34 more

==============================================================================
```

here are the 'duplicate' packages that are being uploaded. https://bintray.com/snowe/maven/Axon-Kotlin/0.1.5#files
the full log is here (if you need debug output let me know) https://travis-ci.com/snowe2010/axon-kotlin/jobs/133849595
here is my entire project, the only 'module' i am trying to deploy is the `axon-kotlin` submodule. https://github.com/snowe2010/axon-kotlin

**Comment by rapekas** [comment]
Hi @eyalbe4 , @AlexeiVainshtein 
my case works smoothly with version 1.8.4. The issue has been resolved.

**Comment by mortezahosseinee** [comment]
Hi, i upload a bintray library and then publish it. this is url that bintray give it to me:

'MapirServiceTest:mapirservice:unspecified'

why?

Here is my code:

install {
    repositories.mavenInstaller {
        // This generates POM.xml with proper parameters
        pom {
            project {
                packaging 'aar'
                // Add your description here
                name '... ... SDK for Android'
                url siteUrl
                groupId properties.getProperty('GROUPID')
                artifactId properties.getProperty('ARTIFACT')
                version properties.getProperty('VERSION_NAME')

                // Set your license
                licenses {
                    license {
                        name 'The Apache Software License, Version 2.0'
                        url 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }
                developers {
                    developer {
                        id '...'
                        name '...'
                        email '...'
                    }
                }
                scm {
                    connection gitUrl
                    developerConnection gitUrl
                    url siteUrl
                }
            }
        }
    }
}

bintray {
    user = properties.getProperty("bintrayUser")
    key = properties.getProperty("bintrayApiKey")

    configurations = ['archives']

    pkg {
        repo = properties.getProperty('REPO')
        name = properties.getProperty('GROUPID')
        userOrg = properties.getProperty('USERORG')
        licenses = ['Apache-2.0']
        vcsUrl = 'https://github.com/bintray/gradle-bintray-plugin.git'
        version {
            name = properties.getProperty('VERSION_NAME')
            desc = properties.getProperty('VERSION_DESC')

            vcsTag = '0.1'
            attributes = ['gradle-plugin': 'com.use.less:com.use.less.gradle:gradle-useless-plugin']
        }
    }
}

task androidJavadocs(type: Javadoc) {
    source = android.sourceSets.main.java.sourceFiles
    classpath = files(android.bootClasspath)
    failOnError false
}

task androidJavadocsJar(type: Jar, dependsOn: androidJavadocs) {
    classifier = 'javadoc'
    from androidJavadocs.destinationDir
}

task androidSourcesJar(type: Jar) {
    classifier = 'sources'
    from android.sourceSets.main.java.sourceFiles
}

artifacts {
    archives androidSourcesJar
    archives androidJavadocsJar
}
